### PR TITLE
Implemented ortoolspy (pmedian) and pulp (knapsack), changed gurobipy (knapsack, fac),

### PR DESCRIPTION
**Pull request by torressa**
Hi again William!

Glad to see you are still working on this repo.

I've been working on implementing ortools using the python wrapper, which seems to work fine (comparable with gurobipy) but will be interesting to implement using C++.
I have no background in C++ but will try my best to implement it.

Also, I will be working expanding the models a little bit to a wider range of problems (rcpsp, maybe vrp). I think we can get some really interesting comparisons. 
So maybe if you leave the pull request open I don't have to open a new one everytime.

Best,
David

### CODE REVIEW

**Comment by whart222** [comment]
@torressa Thanks for these updates. I've started a branch to reorganize the repository to include different categories of information.  I'm going to accept this PR, finalize the reorg, and then you can setup a new PR like you suggest.  I think that's a good idea while you work on new formulations.

If you get a chance, checkout the reorg branch and see what you think.

**Comment by torressa** [comment]
Sounds good!
The reorg branch looks good! I've merged it into the master branch on my fork. 
So this PR probs doesn't make sense until you are ready to merge the branches.

**Comment by whart222** [comment]
@torressa I recently started debating whether it would make more sense to reorganize this repo around the modeling tool.

Specifically, I worked on CUTE examples for POEK, and I realized that it would be crazy to have a separate directory for each.  This suggests the top-level directories should reference modeling tools (Gurobi, Gurobipy, Pyomo, etc), and underneath we have canonical groups of problems, and underneath that we have specific models.

Separately, we could have a directory for comparison scripts, which focus on different points of comparison (e.g. construction runtime vs resolve runtime).

Thoughts?  I don't want to muck with your PR until we finalize the organization, but I've been thinking about this  a bit lately.

**Comment by torressa** [comment]
Hi @whart222! 

Sorry, left it halfway. Partly lost momentum and was also having trouble reproducing results on different machines, gurobi licenses, dependencies...

I think the reorganisation makes sense. For the dependency issue, I'd like to try and separate the build processes and dependencies for each modelling tool. This can be done, at least for the open-source modelling tools, using docker and docker-compose.  To run all the comparisons the requirements are down to: docker / docker-compose.
The split you propose lends itself quite nicely to this as the images can be kept minimal to contain the modelling tool and its specific dependencies and the comparison scripts can be used. This wouldn't work for gurobi, for example, but the rest should be fine.

PS. I've just noticed you've deleted coek! Have you changed the name?

**Comment by whart222** [comment]
FYI, I'm merging this PR.  I want to restart the re-org process.  After I dig into this a bit, I'm sure I'll have more questions...

**Pull request merged**
